"""LCM package __init__.py file
This file automatically generated by lcm-gen.
DO NOT MODIFY BY HAND!!!!
lcm-gen 1.5.2
"""

from .lcmt_target_poses_gui import lcmt_target_poses_gui as lcmt_target_poses_gui
