"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class lcmt_target_poses_gui(object):

    __slots__ = ["timestamp", "num_objects", "goal_mode", "target_positions", "target_orientations", "object_names"]

    __typenames__ = ["int64_t", "int32_t", "int8_t", "double", "double", "string"]

    __dimensions__ = [None, None, None, ["num_objects", 2], ["num_objects", 4], ["num_objects"]]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.num_objects = 0
        """ LCM Type: int32_t """
        self.goal_mode = 0
        """ LCM Type: int8_t """
        self.target_positions = []
        """ LCM Type: double[num_objects][2] """
        self.target_orientations = []
        """ LCM Type: double[num_objects][4] """
        self.object_names = []
        """ LCM Type: string[num_objects] """

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_target_poses_gui._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qib", self.timestamp, self.num_objects, self.goal_mode))
        for i0 in range(self.num_objects):
            buf.write(struct.pack('>2d', *self.target_positions[i0][:2]))
        for i0 in range(self.num_objects):
            buf.write(struct.pack('>4d', *self.target_orientations[i0][:4]))
        for i0 in range(self.num_objects):
            __object_names_encoded = self.object_names[i0].encode('utf-8')
            buf.write(struct.pack('>I', len(__object_names_encoded)+1))
            buf.write(__object_names_encoded)
            buf.write(b"\0")

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_target_poses_gui._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_target_poses_gui._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = lcmt_target_poses_gui()
        self.timestamp, self.num_objects, self.goal_mode = struct.unpack(">qib", buf.read(13))
        self.target_positions = []
        for i0 in range(self.num_objects):
            self.target_positions.append(struct.unpack('>2d', buf.read(16)))
        self.target_orientations = []
        for i0 in range(self.num_objects):
            self.target_orientations.append(struct.unpack('>4d', buf.read(32)))
        self.object_names = []
        for i0 in range(self.num_objects):
            __object_names_len = struct.unpack('>I', buf.read(4))[0]
            self.object_names.append(buf.read(__object_names_len)[:-1].decode('utf-8', 'replace'))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if lcmt_target_poses_gui in parents: return 0
        tmphash = (0x460007315aab09e6) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if lcmt_target_poses_gui._packed_fingerprint is None:
            lcmt_target_poses_gui._packed_fingerprint = struct.pack(">Q", lcmt_target_poses_gui._get_hash_recursive([]))
        return lcmt_target_poses_gui._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcmt_target_poses_gui._get_packed_fingerprint())[0]

