"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class lcmt_target_positions(object):

    __slots__ = ["timestamp", "num_positions", "name", "continuous_mode", "position", "position_names"]

    __typenames__ = ["int64_t", "int32_t", "string", "int8_t", "double", "string"]

    __dimensions__ = [None, None, None, None, ["num_positions"], ["num_positions"]]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.num_positions = 0
        """ LCM Type: int32_t """
        self.name = ""
        """ LCM Type: string """
        self.continuous_mode = 0
        """ LCM Type: int8_t """
        self.position = []
        """ LCM Type: double[num_positions] """
        self.position_names = []
        """ LCM Type: string[num_positions] """

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_target_positions._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.timestamp, self.num_positions))
        __name_encoded = self.name.encode('utf-8')
        buf.write(struct.pack('>I', len(__name_encoded)+1))
        buf.write(__name_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">b", self.continuous_mode))
        buf.write(struct.pack('>%dd' % self.num_positions, *self.position[:self.num_positions]))
        for i0 in range(self.num_positions):
            __position_names_encoded = self.position_names[i0].encode('utf-8')
            buf.write(struct.pack('>I', len(__position_names_encoded)+1))
            buf.write(__position_names_encoded)
            buf.write(b"\0")

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_target_positions._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_target_positions._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = lcmt_target_positions()
        self.timestamp, self.num_positions = struct.unpack(">qi", buf.read(12))
        __name_len = struct.unpack('>I', buf.read(4))[0]
        self.name = buf.read(__name_len)[:-1].decode('utf-8', 'replace')
        self.continuous_mode = struct.unpack(">b", buf.read(1))[0]
        self.position = struct.unpack('>%dd' % self.num_positions, buf.read(self.num_positions * 8))
        self.position_names = []
        for i0 in range(self.num_positions):
            __position_names_len = struct.unpack('>I', buf.read(4))[0]
            self.position_names.append(buf.read(__position_names_len)[:-1].decode('utf-8', 'replace'))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if lcmt_target_positions in parents: return 0
        tmphash = (0x10e84729ebae4dcd) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if lcmt_target_positions._packed_fingerprint is None:
            lcmt_target_positions._packed_fingerprint = struct.pack(">Q", lcmt_target_positions._get_hash_recursive([]))
        return lcmt_target_positions._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcmt_target_positions._get_packed_fingerprint())[0]

