"""LCM package __init__.py file
This file automatically generated by lcm-gen.
DO NOT MODIFY BY HAND!!!!
lcm-gen 1.5.1
"""

from .lcmt_target_positions import lcmt_target_positions as lcmt_target_positions
